import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

Map<String, IconData> iconStringsToIcons = {
  'alcohol': FontAwesomeIcons.whiskeyGlass,
  'beverage': FontAwesomeIcons.glassWater,
  'broth': FontAwesomeIcons.cheese,
  'canned': FontAwesomeIcons.jar,
  'cereal': FontAwesomeIcons.plateWheat,
  'condiment': FontAwesomeIcons.wineBottle,
  'dairy': FontAwesomeIcons.cheese,
  'dressing': FontAwesomeIcons.wineBottle,
  'egg': FontAwesomeIcons.egg,
  'fish': FontAwesomeIcons.fish,
  'fruit': FontAwesomeIcons.appleWhole,
  'grain': FontAwesomeIcons.wheatAwn,
  'herb': FontAwesomeIcons.seedling,
  'hot': FontAwesomeIcons.pepperHot,
  'legume': FontAwesomeIcons.bowlFood,
  'meat': FontAwesomeIcons.bacon,
  'mushroom' : FontAwesomeIcons.meatballCloud,
  'nut': FontAwesomeIcons.stroopwafel,
  'oil': FontAwesomeIcons.bottleDroplet,
  'poultry': FontAwesomeIcons.drumstickBite,
  'sauce': FontAwesomeIcons.wineBottle,
  'seafood': FontAwesomeIcons.shrimp,
  'seasoning': FontAwesomeIcons.jar,
  'seed': FontAwesomeIcons.bowlRice,
  'spice': FontAwesomeIcons.spoon,
  'spread': FontAwesomeIcons.breadSlice,
  'sweetener': FontAwesomeIcons.canadianMapleLeaf,
  'thickener': FontAwesomeIcons.jar,
  'vegetable': FontAwesomeIcons.carrot,
  'vinegar': FontAwesomeIcons.flask,
};
